name: "🔮 MySecurity Pipeline"

on:
  push:
    branches: [ "master", "feature/cmake-pipeline" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    name: 🔎 Analyze
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        language: [ 'cpp' ]

    steps:
    - name: 🧿 Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: ⚡ Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    
    - name: 🪄 Build 
      run: make
      
    - name: 💎 CMake
      uses: threeal/cmake-action@v1.1.0

    - name: ✨ Code Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
